title = "Final Project"
author = "GROUP33"

[player]
starter = "room"
inventory = [
    "beer",
]

####################################################################

# 主角家客廳
[scene.livingroomplayer]
name = "The livingroom of player"
background = "assets/scene/livingroomplayer.bmp"

# 書店
[scene.bookstore]
name = "Bookstore"
background = "assets/scene/bookstore.bmp"

# 老人家門口
[scene.oldpersondoor]
name = "The door of old person"
background = "assets/scene/oldpersondoor.bmp"

# 老人家客廳
[scene.livingroomoldperson]
name = "The livingroom of old person"
background = "assets/scene/livingroomoldperson.bmp"

# 朋友家書房
[scene.bookroom]
name = "The bookroom of friend"
background = "assets/scene/bookroom.bmp"

# 維多利亞時期的街道
[scene.street]
name = "The street of Victoria"
background = "assets/scene/street.bmp"

# 警長沒在住的房子
[scene.policeroom]
name = "The room of police"
background = "assets/scene/policeroom.bmp"

# 時空裂縫
[scene.time]
name = "The time and space rift"
background = "assets/scene/time.bmp"

# 發財結局
[scene.richman]
name = "Be a rich man"
background = "assets/scene/richman.bmp"

# 爸媽快樂結局
[scene.happyending]
name = "reunion"
background = "assets/scene/happyending.bmp"

# 找到寶藏
[scene.findtreasure]
name = "find treasure"
background = "assets/scene/findtreasure.bmp"

# 打給警長
[scene.callingpolice]
name = "call police"
background = "assets/scene/callingpolice.bmp"

# 打給朋友
[scene.callingfriend]
name = "call friend"
background = "assets/scene/callingfriend.bmp"

# 做夢結局
[scene.bedroom]
name = "just a dream"
background = "assets/scene/bedroom.bmp"

# MBTI BEER結局
[scene.lovebeer]
name = "love beer"
background = "assets/scene/lovebeer.bmp"

####################################################################

# 書店老闆
[character.bookstoreowner]
name = "Owner of bookstore"
avatar = "assets/character/bookstoreowner.bmp"

# 老人
[character.oldman]
name = "Old Man"
avatar = "assets/character/oldman.bmp"

# 主角朋友
[character.friend]
name = "Billy (your friend)"
avatar = "assets/character/friend.bmp"

# 主角朋友爸爸
[character.frienddad]
name = "Dad of Billy (Dad of your friend)"
avatar = "assets/character/frienddad.bmp"

# 警長
[character.police]
name = "Police"
avatar = "assets/character/police.bmp"

# 警長在抓ㄉ犯人
[character.criminal]
name = "Criminal"
avatar = "assets/character/criminal.bmp"

# 殺死主角爸媽ㄉ殺手（失業男）
[character.killer]
name = "Killer"
avatar = "assets/character/killer.bmp"

# 主角爸爸
[character.father]
name = "Father"
avatar = "assets/character/father.bmp"

# 主角媽媽
[character.mother]
name = "Mother"
avatar = "assets/character/mother.bmp"

####################################################################

# 啤酒
[item.beer]
name = "Beer"
description = "player's favorite"
icon = "assets/item/beer.bmp"

# 紅色信封袋
[item.envelope]
name = "Envelope"
description = "Red"
icon = "assets/item/envelope.bmp"

# 上面有寫著HELPㄉ摩斯密碼ㄉ紙
[item.paper]
name = "Paper of Morse code"
description = "HELP"
icon = "assets/item/paper.bmp"

# 一張有奇怪符號的紙
[item.symbolpaper]
name = "Symbol Paper"
description = "symbol paper"
icon = "assets/item/symbolpaper.bmp"

# 書店老闆的名片
[item.card]
name = "Card"
description = "card of owner"
icon = "assets/item/card.bmp"

# 穿越手錶
[item.watch]
name = "Watch"
description = "watch with super power"
icon = "assets/item/watch.bmp"

# 偵探衣服
[item.cloth]
name = "Cloth"
description = "cloth of dective"
icon = "assets/item/cloth.bmp"

# 寶藏
[item.treasure]
name = "Treasure"
description = "some gold bars inside"
icon = "assets/item/treasure.bmp"

# 藏寶圖
[item.treasuremap]
name = "Treasure Map"
description = "treasure map"
icon = "assets/item/treasuremap.bmp"

# 有著爸媽照片的項鍊
[item.necklace]
name = "Necklace"
description = "Necklace with parents' photo"
icon = "assets/item/necklace.bmp"

# 一堆金條
[item.goldbar]
name = "Gold Bar"
description = "gold bar"
icon = "assets/item/goldbar.bmp"

####################################################################

[event.room]
scene = "livingroomplayer"
dialogue = "scene1"
item = "envelope"

[dialogue.scene1]
text = """
又是被惡夢喚醒的一天 ⋯
夢裡，我回到了前年聖誕夜
親眼目睹爸爸媽媽被一個失業男子持槍殺死的那天
儘管這件事已經過了兩年
但卻沒有緩和一切
抱著這個沈重的心情
我打算再去冰箱拿一罐酒
但目光卻被放在桌上的黑色信件吸引
我打開來看發現裡面放了一張照片
（這⋯這是啥⋯⋯？）
於是我坐在沙發上盯著這張圖很久⋯⋯之後我決定
"""
[[dialogue.scene1.options]]
text = "解開它"
next = "scene2"
[[dialogue.scene1.options]]
text = "打給我的朋友好了"
event = "calling"

######################################

item = "paper"

[dialogue.scene2]
text = """
這圖片上⋯⋯好像是寫著HELP⋯？？？
"""
[[dialogue.scene2.options]]
text = "太怪了吧？這信件誰放的？"
next = "scene4"
[[dialogue.scene2.options]]
text = "有人遇到危險了？（再喝一口酒壓壓驚）"
event = "final1"

######################################

[event.calling]
scene = "callingfriend"
dialogue = "scene3"

[dialogue.scene3]
text = """
（電話的另一頭傳來）你竟然這個時間點醒著？打給我幹嘛？打麻將喔？
"""
[[dialogue.scene3.options]]
text = "白癡喔，沒啦，最近沒錢，錢都拿去買酒了⋯"
next = "scene5"
[[dialogue.scene3.options]]
text = "（掛掉電話解開它）"
next = "scene2"

######################################

[dialogue.scene5]
text = """
那怎麼啦？發生什麼了嗎？
"""
[[dialogue.scene5.options]]
text = "我剛看到我家桌上放一封信，裡面有一張照片，上面是一堆奇怪的圖案，我拍給你看，你看一下Line"
next = "scene8"
[[dialogue.scene5.options]]
text = "沒事啦（掛電話，突然想自己解開）"
next = "scene2"

######################################

[dialogue.scene8]
text = """
這？這不是摩斯密碼嗎？上面寫這HELP欸？
我爸是摩斯密碼專家，我從小看到大，
差點以為這是我的母語呢⋯⋯（苦笑）
你來跟我爸聊聊吧，他應該會知道這是哪裡來的，
我們都在家，你現在可以過來
"""
[[dialogue.scene8.options]]
text = "別了吧，就不打擾你家人了，既然知道內容了，那我再自己研究一下好了（掛電話）"
next = "scene4"
[[dialogue.scene8.options]]
text = "好啊那我現在去你家"
event = "frienddad"

######################################

item = "card"

[dialogue.scene4]
text = """
將信件往後翻發現裡面還有張名片（書店老闆名片）
所以去了趟書店
"""
[[dialogue.scene4.options]]
text = "（走進店裡）"
event = "bookstore"

######################################

[event.bookstore]
scene = "bookstore"
dialogue = "scene40"
item = "symbolpaper"

[dialogue.scene40]
text = """
（這家書店也太酷！怎麼還放了一堆古文物？）
（發現一張塗鴉，上面記載著奇怪的符號）
"""
[[dialogue.scene40.options]]
text = "老闆，這些符號什麼意思啊？"
next = "scene6"
[[dialogue.scene40.options]]
text = "（暗中研究這些符號的含義）"
event = "bookstore_room"

######################################

[dialogue.scene6]
character = "bookstoreowner"
text = """
這個塗鴉啊，它來自一個非常古老的時代，
那些符號是古代的預言。你感興趣嗎？
"""
[[dialogue.scene6.options]]
text = "非常感興趣，我們能深入談談這個預言嗎？"
next = "scene9"
[[dialogue.scene6.options]]
text = "聽起來有點邪門，我還是自己看看吧。"
event = "bookstore_room"

######################################
# 地址紙條
[dialogue.scene9]
character = "bookstoreowner"
text = """
很久以前，有預言說將會有一位旅行者穿梭時空，
揭開歷史的神秘面紗。
也許，這個人就是你。
這個地址給你，去找他吧！他會告訴你一切的
（書店老闆給你一張寫著地址的紙條）
"""
[[dialogue.scene9.options]]
text = "馬上叫車到那"
event = "door"
[[dialogue.scene9.options]]
text = "車資有點貴⋯⋯我想一下"
next = "scene12"

######################################

[dialogue.scene12]
text = """
（想了很久）
"""
[[dialogue.scene12.options]]
text = "決定用走的過去"
event = "door"
[[dialogue.scene12.options]]
text = "齁好累喔。又不是在玩RPG，叫我一直跑來跑去幹嘛？"
event = "bookstore_room"

######################################

[event.bookstore_room]
scene = "livingroomplayer"
dialogue = "scene7"

[dialogue.scene7]
text = """
（光速逃離）
（回到家）
"""
[[dialogue.scene7.options]]
text = "馬上開一瓶酒喝"
event = "final1"
[[dialogue.scene7.options]]
text = "打給我的朋友好了"
event = "calling"

######################################

[event.frienddad]
scene = "bookroom"
dialogue = "scene10"

[dialogue.scene10]
character = "friend"
text = """
來吧，我爸在書房等你了（走進書房，跟叔叔打過招呼後）
"""
[[dialogue.scene10.options]]
text = "遞給他那張照片"
next = "scene30"

######################################

item = "paper"

[dialogue.scene30]
character = "frienddad"
text = """
這照片！？我記得只有被選中的人才會拿到這張照片⋯
小子，叔叔要告訴你一件嚴肅的事
你是百年難得一見的時空穿越者啊！！！
"""
[[dialogue.scene30.options]]
text = "真的假的⋯⋯"
next = "scene13"
[[dialogue.scene30.options]]
text = "叔叔，我先走了嘿（光速逃離）"
event = "friend_room"

######################################
# 地址紙條
[dialogue.scene13]
character = "frienddad"
text = """
沒錯，你去這裡吧，你會知道一切的。
（遞了一張紙條，上面寫著地址）
"""
[[dialogue.scene13.options]]
text = "馬上搭Uber去（既然是叔叔說的，那我就姑且相信吧）"
event = "door"
[[dialogue.scene13.options]]
text = "齁好累喔。又不是在玩RPG，叫我一直跑來跑去幹嘛？"
event = "bookstore_room"

######################################

[event.friend_room]
scene = "livingroomplayer"
dialogue = "scene14"

[dialogue.scene14]
text = """
（回家後）
（無意見看到信封內好像還有一張紙？）

"""
[[dialogue.scene14.options]]
text = "（走過去瞧瞧）"
next = "scene4"
[[dialogue.scene14.options]]
text = "不管了（從冰箱拿出一罐酒）"
event = "final1"

######################################

[event.door]
scene = "oldpersondoor"
dialogue = "scene11"

[dialogue.scene11]
text = """
（這？看起來像是私人住宅？）
（這真的是我要找的地方嗎？）
（門緩緩自動打開）
"""
[[dialogue.scene11.options]]
text = "（走進去）"
event = "oldpersonhouse"
[[dialogue.scene11.options]]
text = "有點怪欸？"
event = "bookstore_room"

######################################

[event.oldpersonhouse]
scene = "livingroomoldperson"
dialogue = "scene15"

[dialogue.scene15]
character = "oldman"
text = """
你？！竟然出現了啊⋯
找了半輩子終於出現了⋯
過來坐吧！
"""
[[dialogue.scene15.options]]
text = "不聽老人言，吃虧在眼前，聽話過去坐"
next = "scene16"
[[dialogue.scene15.options]]
text = "蛤？瘋了吧？"
event = "bookstore_room"

######################################

item = "treasuremap"

[dialogue.scene16]
character = "oldman"
text = """
你應該很意外自己為什麼在這吧？
你是我們找了很久的時光旅行者
那張塗鴉其實是空白的
對我、對書店老闆及其他人都是
唯獨時光旅行者看得到這上面的符號
不用問為什麼⋯⋯因為我們也不清楚
這都是祖先們世代流傳下來的傳說
我想找你沒有別的原因
你看一下吧
（老人展示了一份看起來年代久遠的藏寶圖）
這是1870年代那時候的藏寶圖
我需要你穿越回去
幫我拿到這個藏寶箱裡面的金條
事成後我會給你九成的酬勞
你願意嗎？
"""
[[dialogue.scene16.options]]
text = "當然好啊有錢誰不賺？"
next = "scene17"
[[dialogue.scene16.options]]
text = "別了吧？講的都啥啊？這是什麼小說劇情才會出現的吧？"
event = "bookstore_room"

######################################

item = "watch"

[dialogue.scene17]
character = "oldman"
text = """
那我給你這個穿越手錶
你只要設定日期並按下這顆按鈕就能穿越到你想去的年代
但我怕你獨吞這筆財產
所以只要你沒在一個月內完成這項任務
這個手錶將會讓你一輩子困在時空裂縫
你將永遠在那裡獨自流浪
你，願意嗎？
"""
[[dialogue.scene17.options]]
text = "沒問題！（反正沒了爸媽我也不是很想活了）"
next = "scene18"
[[dialogue.scene17.options]]
text = "ㄜ？這樣感覺我比較虧欸？（這酬勞誰愛領誰領。）"
event = "bookstore_room"

######################################

item = "treasuremap"

[dialogue.scene18]
character = "oldman"
text = """
（老人把藏寶圖給你）
加油了年輕人
"""
[[dialogue.scene18.options]]
text = "調整手錶日期，穿越回到1870年代"
event = "victoriastreet"

######################################

[event.victoriastreet]
scene = "street"
dialogue = "scene31"

[dialogue.scene31]
character = "police"
text = """
（嗯？這手錶竟然連我的衣服都能換！？
這是什麼福爾摩斯的衣服！？）
（開始端詳衣服，沒注意到有人突然衝過來）
（碰！！！！）
（大跌在地上）
（抬頭發現對面是一個身穿警長制服的人）
你是誰？沒看到我在追人嗎？擋在這幹嘛？
"""
[[dialogue.scene31.options]]
text = "不好意思，我初來乍到不太熟悉這裡，剛剛在低頭想接下來的打算，真的非常抱歉"
next = "scene19"
[[dialogue.scene31.options]]
text = "啊是誰沒在看路？＝＝"
event = "final2"

######################################

[dialogue.scene19]
character = "police"
text = """
新來的？我看你穿著打扮挺像個偵探，
不如你來幫我個忙，我給你地方住吧
"""
[[dialogue.scene19.options]]
text = "好啊請問是什麼忙呢？（ㄏ剛來就遇到盤子）"
next = "scene20"
[[dialogue.scene19.options]]
text = "不好意思，我還有事要做，可能沒辦法幫你。（先找寶藏要緊）"
next = "scene21"

######################################

[dialogue.scene21]
character = "police"
text = """
沒問題的，自己路上小心啊！
"""
[[dialogue.scene21.options]]
text = "（踏上尋找寶藏的旅途）"
event = "findtreasure"

######################################

[event.victoriahouse]
scene = "policeroom"
dialogue = "scene20"

[dialogue.scene20]
character = "police"
text = """
（警長隨即邀請我到他家的空房並拿出一張照片及檔案）
這是我和我的夥伴最近找了很久的逃犯，
他放火燒了一間民宅，導致屋內的一家人死亡，
你看一下照片吧？
還有這個檔案是我們追查到現在有的資訊。
（咦？這不是我之前看到某個網紅講到的歷史事件嗎？
因為太離奇了⋯我一直記到現在呢⋯
正所謂最危險的地方就是最安全的地方，
其實這個犯人後來就一直躲在警長家的地窖⋯⋯
直到警長一家人死去，他才被發現餓死在地窖裡）
"""
[[dialogue.scene20.options]]
text = "好的，我大概從這些檔案中推測到幾個他可能出現的地點，您想聽看看嗎？"
next = "scene22"

######################################

[dialogue.scene22]
character = "police"
text = """
當然，不愧是偵探，
只憑這些文件就能想到他躲藏的地點！
您請說說吧，我馬上帶人過去找！
"""
[[dialogue.scene22.options]]
text = "在您家的酒窖裡"
next = "scene24"

######################################

[event.findtreasure]
scene = "findtreasure"
dialogue = "scene32"

[dialogue.scene32]
text = """
（抵達埋藏點）
（寶藏上面寫著：只能回答一次，
答錯你將被困在這裡一輩子：3 + 4 = ?）
"""
[[dialogue.scene32.options]]
text = "7"
next = "scene23"
[[dialogue.scene32.options]]
text = "12"
event = "final4"

######################################

item = "goldbar"

[dialogue.scene23]
text = """
（寶藏打開了！裡面是滿滿的金條！）
"""
[[dialogue.scene23.options]]
text = "（馬上按下回去按鈕！）"
event = "victoria_old"
[[dialogue.scene23.options]]
text = "既然有了這筆錢，我想幹嘛就幹嘛！（那個手錶的設定應該是唬我的吧？）"
event = "final3"

######################################

[dialogue.scene24]
character = "police"
text = """
！？不可能吧？怎麼可能找了那麼久的犯人在我家？
沒關係，就秉持著對你這人的第一印象，我就信你一回吧
（馬上離開抓犯人）
（隔沒多久，警長打來電話）
"""
[[dialogue.scene24.options]]
text = "接電話"
event = "callingpolice"

######################################

[event.callingpolice]
scene = "callingpolice"
dialogue = "scene33"

[dialogue.scene33]
text = """
多虧你，我終於抓到犯人了！
那房子你想住多久就住多久吧！
"""
[[dialogue.scene33.options]]
text = "沒事沒事，我就借住個幾天我就要走了！"
event = "policebed"
[[dialogue.scene33.options]]
text = "哈！我絕對住爆！"
event = "final6"

######################################

item = "treasure"

[event.victoria_old]
scene = "livingroomoldperson"
dialogue = "scene25"

[dialogue.scene25]
character = "oldman"
text = """
（回到現在2024，老人的家）
你果然不負我的期待，順利帶回寶藏了！
就按照約定，這裡九成你拿走吧！
"""
[[dialogue.scene25.options]]
text = "謝謝你！"
event = "final5"

######################################

[event.policebed]
scene = "policeroom"
dialogue = "scene26"

[dialogue.scene26]
text = """
（傍晚躺在床上）
（好想爸媽啊⋯
如果他們也能知道我今天幫助了人、和我住在這裡，
那該有多好）
"""
[[dialogue.scene26.options]]
text = "（打開放有全家人合照的項鍊）"
next = "scene34"

######################################

item = "necklace"

[dialogue.scene34]
text = """
（！？）
（為什麼！？）
（爸媽的臉怎麼不是之前那樣年輕！？
而是佈滿了皺紋！？難道⋯我改變了歷史？）
"""
[[dialogue.scene34.options]]
text = "按下手錶結束按鈕"
event = "returnhouse"

######################################

[event.returnhouse]
scene = "livingroomplayer"
dialogue = "scene35"

[dialogue.scene35]
character = "mother"
text = """
（回到現在——2024年）
你回來啦？還不去洗手吃飯？
"""
[[dialogue.scene35.options]]
text = "媽媽⋯我好想你（泛著淚眶，抱媽媽）"
next = "scene27"
[[dialogue.scene35.options]]
text = "這是夢吧？（捏了自己的臉）"
event = "final7"

######################################

[dialogue.scene27]
character = "mother"
text = """
傻瓜，哭什麼哭，快來吃飯，
你爸爸今天會晚點回家，你先吃！
（難道爸爸和媽媽因為我改變了歷史復活了？）
"""
[[dialogue.scene27.options]]
text = "好！媽媽！我要永遠黏著你"
event = "final6"
[[dialogue.scene27.options]]
text = "媽媽等我一下！我有急事等等回來跟爸爸一起吃（衝去找老人）"
event = "gooldman"

######################################

[event.gooldman]
scene = "oldpersondoor"
dialogue = "scene36"

[dialogue.scene36]
text = """
（門又自動打開了？他是自動門？
誰家的門會做自動門？）
"""
[[dialogue.scene36.options]]
text = "走進去"
event = "oldmanhouse"

######################################

[event.oldmanhouse]
scene = "livingroomoldperson"
dialogue = "scene28"

[dialogue.scene28]
character = "oldman"
text = """
進來吧！找到寶藏了嗎？
"""
[[dialogue.scene28.options]]
text = "還沒，但我不想找了，我爸爸媽媽回來了⋯⋯有了爸媽，那些錢我都不想要了"
next = "scene29"

######################################

[dialogue.scene29]
character = "oldman"
text = """
難道你做了什麼改變了未來嗎？
（老人掐指一算）
你！？你抓到當年的犯人了！？
難怪你爸媽會死而復生⋯
那犯人就是殺死你父母兇手的祖先啊⋯
真是個幸運的孩子，你回去好好陪爸媽吧！
這些財富我就留給下一個人來幫我尋找了
"""
[[dialogue.scene29.options]]
text = "謝謝你！"
event = "final8"

######################################

[event.final1]
scene = "lovebeer"
dialogue = "ending1"

[dialogue.ending1]
text = """
你的MBTI⋯是BEER吧？
"""

######################################

[event.final2]
scene = "time"
dialogue = "ending2"

[dialogue.ending2]
text = """
（警長覺得你很可疑）
（把你抓去牢房裡監禁一個月）
因此你被困在時空裂縫裡
成為了時間的流浪者。
"""

######################################

[event.final3]
scene = "time"
dialogue = "ending3"

[dialogue.ending3]
text = """
爽花這些錢過了一個月⋯
你被困在時空裂縫裡
成為了時間的流浪者。
"""

######################################

[event.final4]
scene = "time"
dialogue = "ending4"

[dialogue.ending4]
text = """
因為答錯了，你因此待在這裡超過一個月
最後，你被困在時空裂縫裡
成為了時間的流浪者。
"""

######################################

[event.final5]
scene = "richman"
dialogue = "ending5"

[dialogue.ending5]
text = """
你成為了一個富豪
而且你將這些錢全部ALL IN NVIDIA的股票
因為這些股票
你在2024年成功擠進全球前百名富豪行列！
"""

######################################

[event.final6]
scene = "time"
dialogue = "ending6"

[dialogue.ending6]
text = """
因為忘記一個月的期限了⋯⋯你被困在時空裂縫裡
成為了時間的流浪者。
"""

######################################

[event.final7]
scene = "bedroom"
dialogue = "ending7"

[dialogue.ending7]
text = """
（啊！好痛！）
（果然⋯這真的是一場夢）
"""

######################################

[event.final8]
scene = "happyending"
dialogue = "ending8"

[dialogue.ending8]
text = """
和爸媽過著幸福快樂的生活！
"""

######################################